feat: add phone international field
ems-project/EMSFormBundle pull request #243
Opened 2021-09-29 19:49 UTC by coppee

|Q              |A  |
|---------------|---|
|Bug fix?       |N|
|New feature?   |Y|	
|BC breaks?     |N|	
|Deprecations?  |N|	
|Fixed tickets  |N|

2021-09-30 14:27 UTC, Davidmattei requested changes

2021-09-30 14:27 UTC, Davidmattei commented on src/Components/Field/InternationalPhone.php
> +
```suggestion
declare(strict_types=1);
```

2021-09-30 14:27 UTC, Davidmattei commented on src/Components/Field/InternationalPhone.php
> +        if (!empty($this->config->getChoiceList())) {
No empty \count

2021-09-30 15:30 UTC, coppee commented on src/Components/Field/InternationalPhone.php
> +
Done

2021-09-30 15:30 UTC, coppee commented on src/Components/Field/InternationalPhone.php
> +        if (!empty($this->config->getChoiceList())) {
Done

2021-09-30 18:37 UTC, theus77 approved these changes

2021-10-01 06:16 UTC, Davidmattei approved these changes

2021-10-01 06:16 UTC, merged